title: "Lillian B. Hughes Wyatt"
author: "Lillian Hughes Wyatt"
description: "Caltech"
permalink: /:title/
lang: "en"
excerpt_separator: "\n\n\n"
date_format: "%B %d, %Y"

# Layout

show_excerpts: false            # show article excerpts instead of archive list on the home page
show_frame: true              # display a grey frame on large screens
show_sidebar: false             # show a sidebar instead of the usual header
show_minimal: false             # remove all clutter

#show_frame: "/assets/images/background.svg"

# Menu                          # for available icons see https://fontawesome.com/v5/icons/

navigation:                     # accepts {file, title, url, icon, sidebaricon}
  - {file: "LillianCV.pdf", title: "CV", sidebaricon: home}
  - {file: "blog.md", title: "Blog", sidebaricon: address-card}
  - {title: "Google Scholar", url: "https://scholar.google.com/citations?user=F4FMwhsAAAAJ&hl=en"}

external:                       # accepts {file, title, url, icon, sidebaricon}
  - {title: Mail, icon: envelope, url: "mailto:lbhwyatt@caltech.edu"}
  - {title: Github, icon: github, url: "https://github.com/lillianhugheswyatt"}
  #- {title: Subscribe, icon: rss, url: "/feed.xml"}

comments:
#  disqus_shortname: ""         # see https://disqus.com
#  isso_domain: ""              # see https://isso-comments.de

plugins:
 - jekyll-feed
